//EXERCISE 5

//write a js program to pretend to look like a hacker write an async funtion
//which will simply display the following output:
/*
Initialising hack program....
Hacking Ashish username...
username found ashish17... 
connecting to facebook.... 
try to use html and styling if possible
*/